In [6]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

In [7]:
digits = load_digits()

In [9]:
df = pd.DataFrame(digits.data)
df.shape

(1797, 64)

In [10]:
len(digits.target)

1797

In [12]:
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [17]:
lr = LogisticRegression()
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)

C:\Users\imaru\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [21]:
rf = RandomForestClassifier(n_estimators = 500)
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.9592592592592593

In [22]:
svm = SVC()
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.9796296296296296

In [23]:
# WE see that varying training sizes can affect the test scores of various models, so comparing these models with train,test--
#split is not accurate and preferred
# We do K Fold Cross Validation now

In [27]:
digits.data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [33]:
digits.target[0:12]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

In [47]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [48]:
from sklearn.model_selection import KFold
kf = KFold(n_splits =2)
kf

KFold(n_splits=2, random_state=None, shuffle=False)

In [49]:
#EXAMPLE OF SPLIT INDICES
for train_index, test_index in kf.split([1,2,3,4,5]):
    print(train_index,test_index)

[3 4] [0 1 2]
[0 1 2] [3 4]


In [50]:
from sklearn.model_selection import StratifiedKFold
sk = StratifiedKFold(n_splits = 3)

In [53]:
log = [] #for storing score of Logistic Regression model
svc = [] #for storing score of Support Vector Machine model
randomForest = [] #for storing score of Random Forest model


for train_index, test_index in sk.split(digits.data,digits.target):
    X_train,X_test,Y_train,Y_test = digits.data[train_index], digits.data[test_index],\
                                        digits.target[train_index],digits.target[test_index]
    
    log.append(get_score(LogisticRegression(),X_train,X_test,Y_train,Y_test))
    svc.append(get_score(SVC(),X_train,X_test,Y_train,Y_test))
    randomForest.append(get_score(RandomForestClassifier(n_estimators = 40),X_train,X_test,Y_train,Y_test))
    


C:\Users\imaru\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\imaru\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [54]:
log

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [55]:
svc

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [56]:
randomForest

[0.9398998330550918, 0.9465776293823038, 0.9198664440734557]